import AVFoundation
import Accelerate
import Foundation

/// Failures produced by native audio loading, analysis, and engine control.
public enum P5AudioError: Error, Sendable, Hashable, LocalizedError {
    /// AVFoundation could not open an audio file.
    case fileLoadingFailed(String)
    /// AVAudioEngine could not begin rendering.
    case engineStartFailed(String)
    /// A requested file-player timestamp is outside the file timeline.
    case invalidTime
    /// A PCM buffer does not expose finite Float32 samples.
    case invalidSamples
    /// Accelerate could not allocate the requested Fourier transform.
    case analyzerCreationFailed(String)
    /// AVFoundation could not create a mono oscillator stream format.
    case formatCreationFailed
    /// The engine already has an output analyzer tap.
    case analyzerAlreadyInstalled

    /// A localized description suitable for diagnostics and user interfaces.
    public var errorDescription: String? {
        switch self {
        case .fileLoadingFailed(let reason):
            "The audio file could not be loaded: \(reason)"
        case .engineStartFailed(let reason):
            "The native audio engine could not start: \(reason)"
        case .invalidTime:
            "Audio time must be finite, nonnegative, and within the file duration."
        case .invalidSamples:
            "Audio analysis requires finite Float32 PCM samples and a positive sample rate."
        case .analyzerCreationFailed(let reason):
            "The audio analyzer could not be created: \(reason)"
        case .formatCreationFailed:
            "AVFoundation could not create the oscillator audio format."
        case .analyzerAlreadyInstalled:
            "The audio engine already has an output analyzer installed."
        }
    }
}

/// Validated metadata for a local AVFoundation audio file.
public struct P5AudioFile: Sendable {
    /// Local source URL.
    public let url: URL
    /// File duration in seconds.
    public let duration: Double
    /// Native processing sample rate in hertz.
    public let sampleRate: Double
    /// Number of interleaved or noninterleaved audio channels.
    public let channelCount: Int

    /// Opens a local file and loads its native processing metadata.
    public init(url: URL) throws {
        try self.init(url: url, runtime: P5AudioFileRuntime())
    }

    init(url: URL, runtime: P5AudioFileRuntime) throws {
        do {
            let file = try runtime.open(url)
            let sampleRate = file.processingFormat.sampleRate
            let channelCount = Int(file.processingFormat.channelCount)
            let duration = Double(file.length) / sampleRate
            guard
                file.length > 0,
                sampleRate.isFinite && sampleRate > 0,
                channelCount > 0,
                duration.isFinite && duration >= 0
            else {
                throw P5AudioError.fileLoadingFailed(
                    "AVFoundation returned invalid file metadata."
                )
            }
            self.url = url
            self.duration = duration
            self.sampleRate = sampleRate
            self.channelCount = channelCount
        } catch let error as P5AudioError {
            throw error
        } catch {
            throw P5AudioError.fileLoadingFailed(error.localizedDescription)
        }
    }
}

/// Periodic waveforms generated by ``P5Oscillator``.
public enum P5OscillatorWaveform: String, Sendable, Hashable, Codable, CaseIterable {
    /// Smooth sinusoidal waveform.
    case sine
    /// Bipolar square waveform.
    case square
    /// Rising bipolar sawtooth waveform.
    case sawtooth
    /// Symmetric bipolar triangle waveform.
    case triangle
}

/// An attack-decay-sustain-release amplitude envelope.
public struct P5AudioEnvelope: Sendable, Hashable, Codable {
    private enum CodingKeys: String, CodingKey {
        case attackTime, decayTime, sustainLevel, releaseTime
    }

    /// Attack duration in seconds.
    public let attackTime: Double
    /// Decay duration in seconds.
    public let decayTime: Double
    /// Sustained amplitude in the closed range `0...1`.
    public let sustainLevel: Float
    /// Release duration in seconds.
    public let releaseTime: Double

    /// Creates a validated ADSR envelope.
    ///
    /// - Precondition: Durations are finite and nonnegative and sustain level is finite in
    ///   `0...1`.
    public init(
        attackTime: Double = 0.01,
        decayTime: Double = 0.1,
        sustainLevel: Float = 0.8,
        releaseTime: Double = 0.2
    ) {
        precondition(attackTime.isFinite && attackTime >= 0)
        precondition(decayTime.isFinite && decayTime >= 0)
        precondition(sustainLevel.isFinite && (0...1).contains(sustainLevel))
        precondition(releaseTime.isFinite && releaseTime >= 0)
        self.attackTime = attackTime
        self.decayTime = decayTime
        self.sustainLevel = sustainLevel
        self.releaseTime = releaseTime
    }

    /// Returns normalized envelope amplitude at an elapsed timeline position.
    ///
    /// When `releaseAt` is supplied, release starts from the envelope value at that time.
    ///
    /// - Precondition: Times are finite and nonnegative.
    public func amplitude(at elapsedTime: Double, releaseAt: Double? = nil) -> Float {
        precondition(elapsedTime.isFinite && elapsedTime >= 0)
        precondition(releaseAt.map { $0.isFinite && $0 >= 0 } ?? true)
        return amplitudeUnchecked(at: elapsedTime, releaseAt: releaseAt)
    }

    /// Decodes an envelope while preserving every public value invariant.
    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let attackTime = try container.decode(Double.self, forKey: .attackTime)
        let decayTime = try container.decode(Double.self, forKey: .decayTime)
        let sustainLevel = try container.decode(Float.self, forKey: .sustainLevel)
        let releaseTime = try container.decode(Double.self, forKey: .releaseTime)
        guard
            attackTime.isFinite && attackTime >= 0,
            decayTime.isFinite && decayTime >= 0,
            sustainLevel.isFinite && (0...1).contains(sustainLevel),
            releaseTime.isFinite && releaseTime >= 0
        else {
            throw DecodingError.dataCorrupted(
                .init(codingPath: decoder.codingPath, debugDescription: "Invalid ADSR envelope.")
            )
        }
        self.init(
            attackTime: attackTime,
            decayTime: decayTime,
            sustainLevel: sustainLevel,
            releaseTime: releaseTime
        )
    }

    /// Encodes all envelope stages using stable field names.
    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attackTime, forKey: .attackTime)
        try container.encode(decayTime, forKey: .decayTime)
        try container.encode(sustainLevel, forKey: .sustainLevel)
        try container.encode(releaseTime, forKey: .releaseTime)
    }

    func amplitudeUnchecked(at elapsedTime: Double, releaseAt: Double?) -> Float {
        if let releaseAt, elapsedTime >= releaseAt {
            guard releaseTime > 0 else { return 0 }
            let initial = amplitudeUnchecked(at: releaseAt, releaseAt: nil)
            let progress = min(1, (elapsedTime - releaseAt) / releaseTime)
            return initial * Float(1 - progress)
        }
        if attackTime > 0, elapsedTime < attackTime {
            return Float(elapsedTime / attackTime)
        }
        let decayElapsed = elapsedTime - attackTime
        if decayTime > 0, decayElapsed < decayTime {
            let progress = Float(decayElapsed / decayTime)
            return 1 - ((1 - sustainLevel) * progress)
        }
        return sustainLevel
    }
}

/// One immutable amplitude and frequency-domain analysis result.
public struct P5AudioAnalysis: Sendable, Hashable, Codable {
    private enum CodingKeys: String, CodingKey {
        case amplitude, spectrum, sampleRate, fftSize
    }

    /// Root-mean-square amplitude of the analyzed samples.
    public let amplitude: Float
    /// Linear magnitude for each FFT bin below the Nyquist frequency.
    public let spectrum: [Float]
    /// Sample rate used for frequency-bin interpretation.
    public let sampleRate: Double
    /// Transform size used to produce `spectrum`.
    public let fftSize: Int

    /// Creates a validated analysis snapshot.
    ///
    /// - Precondition: Values are finite and nonnegative, sample rate is positive, FFT size is a
    ///   power of two, and spectrum contains exactly half as many bins as the transform size.
    public init(amplitude: Float, spectrum: [Float], sampleRate: Double, fftSize: Int) {
        precondition(amplitude.isFinite && amplitude >= 0)
        precondition(sampleRate.isFinite && sampleRate > 0)
        precondition(fftSize >= 2 && fftSize.isMultiple(of: 2) && fftSize.nonzeroBitCount == 1)
        precondition(spectrum.count == fftSize / 2)
        precondition(spectrum.allSatisfy { $0.isFinite && $0 >= 0 })
        self.amplitude = amplitude
        self.spectrum = spectrum
        self.sampleRate = sampleRate
        self.fftSize = fftSize
    }

    /// Returns the lower-edge frequency represented by a spectrum bin.
    ///
    /// - Precondition: `bin` is a valid spectrum index.
    public func frequency(forBin bin: Int) -> Double {
        precondition(spectrum.indices.contains(bin))
        return Double(bin) * sampleRate / Double(fftSize)
    }

    /// Decodes a snapshot while preserving FFT shape and finite-value invariants.
    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let amplitude = try container.decode(Float.self, forKey: .amplitude)
        let spectrum = try container.decode([Float].self, forKey: .spectrum)
        let sampleRate = try container.decode(Double.self, forKey: .sampleRate)
        let fftSize = try container.decode(Int.self, forKey: .fftSize)
        guard
            amplitude.isFinite && amplitude >= 0,
            sampleRate.isFinite && sampleRate > 0,
            fftSize >= 2 && fftSize.isMultiple(of: 2) && fftSize.nonzeroBitCount == 1,
            spectrum.count == fftSize / 2,
            spectrum.allSatisfy({ $0.isFinite && $0 >= 0 })
        else {
            throw DecodingError.dataCorrupted(
                .init(codingPath: decoder.codingPath, debugDescription: "Invalid audio analysis.")
            )
        }
        self.init(
            amplitude: amplitude,
            spectrum: spectrum,
            sampleRate: sampleRate,
            fftSize: fftSize
        )
    }

    /// Encodes the amplitude, spectrum, sample rate, and transform size.
    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amplitude, forKey: .amplitude)
        try container.encode(spectrum, forKey: .spectrum)
        try container.encode(sampleRate, forKey: .sampleRate)
        try container.encode(fftSize, forKey: .fftSize)
    }
}

/// Accelerate-backed output or offline amplitude and FFT analyzer.
public final class P5AudioAnalyzer: @unchecked Sendable {
    /// Power-of-two transform size.
    public let fftSize: Int
    private let transform: vDSP.DiscreteFourierTransform<Float>
    private let lock = NSLock()
    private var storedLatest: P5AudioAnalysis?

    /// Creates an analyzer for transforms from 32 through 32,768 samples.
    ///
    /// - Precondition: `fftSize` is a power of two in `32...32_768`.
    public convenience init(fftSize: Int = 1_024) throws {
        try self.init(fftSize: fftSize, runtime: P5AudioAnalysisRuntime())
    }

    init(fftSize: Int, runtime: P5AudioAnalysisRuntime) throws {
        precondition(
            (32...32_768).contains(fftSize) && fftSize.nonzeroBitCount == 1
        )
        self.fftSize = fftSize
        do {
            transform = try runtime.makeTransform(fftSize)
        } catch {
            throw P5AudioError.analyzerCreationFailed(error.localizedDescription)
        }
    }

    /// Most recent result installed by ``process(_:)``, or `nil` before the first buffer.
    public var latest: P5AudioAnalysis? {
        lock.withLock { storedLatest }
    }

    /// Analyzes finite mono samples, truncating old samples or zero-padding to `fftSize`.
    public func analyze(samples: [Float], sampleRate: Double) throws -> P5AudioAnalysis {
        guard
            samples.isEmpty == false,
            samples.allSatisfy(\.isFinite),
            sampleRate.isFinite && sampleRate > 0
        else {
            throw P5AudioError.invalidSamples
        }
        let selected = samples.suffix(fftSize)
        let amplitude = vDSP.rootMeanSquare(selected)
        var inputReal = Array(selected)
        if inputReal.count < fftSize {
            inputReal.append(contentsOf: repeatElement(0, count: fftSize - inputReal.count))
        }
        let window = vDSP.window(
            ofType: Float.self,
            usingSequence: .hanningDenormalized,
            count: fftSize,
            isHalfWindow: false
        )
        vDSP.multiply(inputReal, window, result: &inputReal)

        let inputImaginary = [Float](repeating: 0, count: fftSize)
        var outputReal = [Float](repeating: 0, count: fftSize)
        var outputImaginary = [Float](repeating: 0, count: fftSize)
        transform.transform(
            inputReal: inputReal,
            inputImaginary: inputImaginary,
            outputReal: &outputReal,
            outputImaginary: &outputImaginary
        )
        var magnitudes = [Float](repeating: 0, count: fftSize / 2)
        let scale = Float(2) / Float(fftSize)
        for index in magnitudes.indices {
            magnitudes[index] = hypot(outputReal[index], outputImaginary[index]) * scale
        }
        return P5AudioAnalysis(
            amplitude: amplitude,
            spectrum: magnitudes,
            sampleRate: sampleRate,
            fftSize: fftSize
        )
    }

    /// Analyzes the first Float32 channel of a native PCM buffer and stores the result.
    @discardableResult
    public func process(_ buffer: AVAudioPCMBuffer) throws -> P5AudioAnalysis {
        guard
            let channels = buffer.floatChannelData,
            buffer.format.channelCount > 0,
            buffer.frameLength > 0
        else {
            throw P5AudioError.invalidSamples
        }
        let samples = Array(
            UnsafeBufferPointer(start: channels[0], count: Int(buffer.frameLength))
        )
        let analysis = try analyze(samples: samples, sampleRate: buffer.format.sampleRate)
        lock.withLock { storedLatest = analysis }
        return analysis
    }
}

/// Observable lifecycle states for ``P5AudioEngine``.
public enum P5AudioEngineState: Sendable, Hashable, Codable {
    /// Engine resources are allocated but not rendering.
    case stopped
    /// The engine is actively rendering audio.
    case running
    /// Rendering paused because the app or caller suspended it.
    case paused
    /// Native startup failed.
    case failed(String)
}

/// Main-actor AVAudioEngine host for P5 file players, oscillators, and analysis.
@MainActor
public final class P5AudioEngine {
    /// Native engine for advanced Apple-platform routing and diagnostics.
    public let nativeEngine: AVAudioEngine
    /// Current explicit rendering lifecycle state.
    public private(set) var state = P5AudioEngineState.stopped
    /// Called on the main actor after every lifecycle transition.
    public var stateChanged: (@MainActor @Sendable (P5AudioEngineState) -> Void)?

    private let runtime: P5AudioEngineRuntime
    private let cleanup: P5AudioEngineCleanup
    private var installedAnalyzer: P5AudioAnalyzer?

    /// Creates a stopped engine without activating the platform audio session.
    public convenience init() {
        self.init(nativeEngine: AVAudioEngine(), runtime: P5AudioEngineRuntime())
    }

    init(nativeEngine: AVAudioEngine, runtime: P5AudioEngineRuntime) {
        self.nativeEngine = nativeEngine
        self.runtime = runtime
        cleanup = P5AudioEngineCleanup(engine: nativeEngine, runtime: runtime)
    }

    /// Main-mixer output volume in the closed range `0...1`.
    public var outputVolume: Float {
        get { runtime.outputVolume(nativeEngine.mainMixerNode) }
        set {
            precondition(newValue.isFinite && (0...1).contains(newValue))
            runtime.setOutputVolume(nativeEngine.mainMixerNode, newValue)
        }
    }

    /// Prepares and starts rendering, preserving native startup diagnostics.
    public func start() throws {
        do {
            runtime.prepare(nativeEngine)
            try runtime.start(nativeEngine)
            transition(to: .running)
        } catch {
            let failure = P5AudioError.engineStartFailed(error.localizedDescription)
            transition(to: .failed(failure.localizedDescription))
            throw failure
        }
    }

    /// Pauses rendering while preserving node timelines.
    public func pause() {
        runtime.pause(nativeEngine)
        transition(to: .paused)
    }

    /// Stops rendering and resets attached node timelines.
    public func stop() {
        runtime.stop(nativeEngine)
        runtime.reset(nativeEngine)
        transition(to: .stopped)
    }

    /// Pauses active audio whenever the host scene becomes inactive or backgrounded.
    ///
    /// Returning active never starts or resumes audio implicitly.
    public func scenePhaseChanged(to phase: P5ScenePhase) {
        if phase != .active && state == .running {
            pause()
        }
    }

    /// Creates and connects a controllable mono oscillator to the main mixer.
    public func makeOscillator(
        waveform: P5OscillatorWaveform = .sine,
        frequency: Double = 440,
        amplitude: Float = 0.5
    ) throws -> P5Oscillator {
        let negotiatedSampleRate = runtime.outputFormat(nativeEngine.mainMixerNode).sampleRate
        let sampleRate =
            negotiatedSampleRate.isFinite && negotiatedSampleRate > 0
            ? negotiatedSampleRate
            : 44_100
        let renderState = P5OscillatorRenderState(
            waveform: waveform,
            frequency: frequency,
            amplitude: amplitude
        )
        guard let format = runtime.makeFormat(sampleRate) else {
            throw P5AudioError.formatCreationFailed
        }
        let node = runtime.makeSourceNode(format) { frameCount, buffers in
            renderState.render(
                frameCount: Int(frameCount),
                sampleRate: sampleRate,
                buffers: buffers
            )
        }
        runtime.attach(nativeEngine, node)
        runtime.connect(nativeEngine, node, nativeEngine.mainMixerNode, format)
        return P5Oscillator(nativeNode: node, renderState: renderState)
    }

    /// Opens, attaches, and connects a native file player to the main mixer.
    public func makeFilePlayer(for file: P5AudioFile) throws -> P5AudioFilePlayer {
        do {
            let nativeFile = try runtime.openFile(file.url)
            let node = runtime.makePlayerNode()
            runtime.attach(nativeEngine, node)
            runtime.connect(
                nativeEngine, node, nativeEngine.mainMixerNode, nativeFile.processingFormat)
            return P5AudioFilePlayer(
                file: file,
                nativeFile: nativeFile,
                nativeNode: node,
                runtime: P5AudioPlayerRuntime()
            )
        } catch let error as P5AudioError {
            throw error
        } catch {
            throw P5AudioError.fileLoadingFailed(error.localizedDescription)
        }
    }

    /// Installs one analyzer tap on the main-mixer output.
    public func installAnalyzer(_ analyzer: P5AudioAnalyzer) throws {
        guard installedAnalyzer == nil else {
            throw P5AudioError.analyzerAlreadyInstalled
        }
        runtime.installTap(
            nativeEngine.mainMixerNode,
            AVAudioFrameCount(analyzer.fftSize)
        ) { buffer in
            _ = try? analyzer.process(buffer)
        }
        installedAnalyzer = analyzer
        cleanup.setTapInstalled(true)
    }

    /// Removes the current analyzer tap, if any.
    public func removeAnalyzer() {
        guard installedAnalyzer != nil else { return }
        runtime.removeTap(nativeEngine.mainMixerNode)
        installedAnalyzer = nil
        cleanup.setTapInstalled(false)
    }

    private func transition(to state: P5AudioEngineState) {
        self.state = state
        stateChanged?(state)
    }
}

/// Main-actor controller for a render-thread-safe periodic AVAudioSourceNode.
@MainActor
public final class P5Oscillator {
    /// Native source node for advanced AVAudioEngine routing.
    public let nativeNode: AVAudioSourceNode
    private let renderState: P5OscillatorRenderState

    init(nativeNode: AVAudioSourceNode, renderState: P5OscillatorRenderState) {
        self.nativeNode = nativeNode
        self.renderState = renderState
    }

    /// Current periodic waveform.
    public var waveform: P5OscillatorWaveform {
        get { renderState.waveform }
        set { renderState.waveform = newValue }
    }

    /// Oscillator frequency in hertz.
    public var frequency: Double {
        get { renderState.frequency }
        set {
            precondition(newValue.isFinite && newValue > 0)
            renderState.frequency = newValue
        }
    }

    /// Peak oscillator amplitude in the closed range `0...1`.
    public var amplitude: Float {
        get { renderState.amplitude }
        set {
            precondition(newValue.isFinite && (0...1).contains(newValue))
            renderState.amplitude = newValue
        }
    }

    /// Whether the source currently produces its waveform instead of silence.
    public var isPlaying: Bool { renderState.isPlaying }

    /// Starts a steady oscillator without an amplitude envelope.
    public func play() {
        renderState.play()
    }

    /// Starts the oscillator and resets the supplied ADSR envelope timeline.
    public func trigger(envelope: P5AudioEnvelope = P5AudioEnvelope()) {
        renderState.trigger(envelope: envelope)
    }

    /// Starts the release stage of the active envelope, or stops a steady oscillator.
    public func release() {
        renderState.release()
    }

    /// Stops output and resets phase and envelope state.
    public func stop() {
        renderState.stop()
    }
}

/// Observable transport states for ``P5AudioFilePlayer``.
public enum P5AudioFilePlayerState: Sendable, Hashable, Codable {
    /// The file is stopped at its beginning.
    case stopped
    /// Native playback is requested.
    case playing
    /// Playback is paused at its current native position.
    case paused
    /// The scheduled file or segment reached its end.
    case ended
}

/// Main-actor AVAudioPlayerNode controller for one local audio file.
@MainActor
public final class P5AudioFilePlayer {
    /// Audio file and immutable metadata represented by this player.
    public let file: P5AudioFile
    /// Native player node for advanced AVAudioEngine routing.
    public let nativeNode: AVAudioPlayerNode
    /// Current deterministic transport state.
    public private(set) var state = P5AudioFilePlayerState.stopped
    /// Whether the complete file restarts automatically after reaching its end.
    public var loops = false
    /// Called on the main actor after every transport transition.
    public var stateChanged: (@MainActor @Sendable (P5AudioFilePlayerState) -> Void)?

    private let nativeFile: AVAudioFile
    private let runtime: P5AudioPlayerRuntime
    private var scheduled = false

    init(
        file: P5AudioFile,
        nativeFile: AVAudioFile,
        nativeNode: AVAudioPlayerNode,
        runtime: P5AudioPlayerRuntime
    ) {
        self.file = file
        self.nativeFile = nativeFile
        self.nativeNode = nativeNode
        self.runtime = runtime
    }

    /// Player-node volume in the closed range `0...1`.
    public var volume: Float {
        get { runtime.volume(nativeNode) }
        set {
            precondition(newValue.isFinite && (0...1).contains(newValue))
            runtime.setVolume(nativeNode, newValue)
        }
    }

    /// Stereo pan in the closed range `-1...1`.
    public var pan: Float {
        get { runtime.pan(nativeNode) }
        set {
            precondition(newValue.isFinite && (-1...1).contains(newValue))
            runtime.setPan(nativeNode, newValue)
        }
    }

    /// Schedules from the current logical position and requests playback.
    public func play() {
        if scheduled == false || state == .ended {
            schedule(from: 0)
        }
        runtime.play(nativeNode)
        transition(to: .playing)
    }

    /// Pauses without discarding the scheduled native segment.
    public func pause() {
        runtime.pause(nativeNode)
        transition(to: .paused)
    }

    /// Stops playback and resets the next play request to the file beginning.
    public func stop() {
        runtime.stop(nativeNode)
        scheduled = false
        transition(to: .stopped)
    }

    /// Reschedules playback from a validated position in the file timeline.
    public func seek(to time: Double) throws {
        guard time.isFinite && time >= 0 && time <= file.duration else {
            throw P5AudioError.invalidTime
        }
        let shouldResume = state == .playing
        runtime.stop(nativeNode)
        if time == file.duration {
            scheduled = false
            transition(to: .ended)
            return
        }
        schedule(from: time)
        if shouldResume {
            runtime.play(nativeNode)
            transition(to: .playing)
        } else {
            transition(to: .paused)
        }
    }

    private func schedule(from time: Double) {
        let startFrame = min(
            nativeFile.length,
            AVAudioFramePosition((time * file.sampleRate).rounded(.down))
        )
        let remaining = max(0, nativeFile.length - startFrame)
        runtime.schedule(
            nativeNode,
            nativeFile,
            startFrame,
            AVAudioFrameCount(clamping: remaining)
        ) {
            Task { @MainActor [weak self] in self?.reachedEnd() }
        }
        scheduled = true
    }

    private func reachedEnd() {
        scheduled = false
        if loops {
            play()
        } else {
            transition(to: .ended)
        }
    }

    private func transition(to state: P5AudioFilePlayerState) {
        self.state = state
        stateChanged?(state)
    }
}

final class P5OscillatorRenderState: @unchecked Sendable {
    private struct State {
        var waveform: P5OscillatorWaveform
        var frequency: Double
        var amplitude: Float
        var phase = 0.0
        var samplePosition = 0
        var isPlaying = false
        var envelope: P5AudioEnvelope?
        var releaseAt: Double?
    }

    private let lock = NSLock()
    private var state: State

    init(waveform: P5OscillatorWaveform, frequency: Double, amplitude: Float) {
        precondition(frequency.isFinite && frequency > 0)
        precondition(amplitude.isFinite && (0...1).contains(amplitude))
        state = State(waveform: waveform, frequency: frequency, amplitude: amplitude)
    }

    var waveform: P5OscillatorWaveform {
        get { lock.withLock { state.waveform } }
        set { lock.withLock { state.waveform = newValue } }
    }

    var frequency: Double {
        get { lock.withLock { state.frequency } }
        set { lock.withLock { state.frequency = newValue } }
    }

    var amplitude: Float {
        get { lock.withLock { state.amplitude } }
        set { lock.withLock { state.amplitude = newValue } }
    }

    var isPlaying: Bool { lock.withLock { state.isPlaying } }

    func play() {
        lock.withLock {
            state.isPlaying = true
            state.envelope = nil
            state.releaseAt = nil
        }
    }

    func trigger(envelope: P5AudioEnvelope) {
        lock.withLock {
            state.isPlaying = true
            state.samplePosition = 0
            state.envelope = envelope
            state.releaseAt = nil
        }
    }

    func release() {
        lock.withLock {
            guard let envelope = state.envelope else {
                state.isPlaying = false
                return
            }
            if state.releaseAt == nil {
                state.releaseAt = Double(state.samplePosition)
            }
            state.envelope = envelope
        }
    }

    func stop() {
        lock.withLock {
            state.isPlaying = false
            state.phase = 0
            state.samplePosition = 0
            state.envelope = nil
            state.releaseAt = nil
        }
    }

    func render(
        frameCount: Int,
        sampleRate: Double,
        buffers: UnsafeMutableAudioBufferListPointer
    ) {
        lock.withLock {
            for frame in 0..<frameCount {
                let elapsed = Double(state.samplePosition) / sampleRate
                let releaseAt = state.releaseAt.map { $0 / sampleRate }
                let envelopeAmplitude =
                    state.envelope?.amplitudeUnchecked(
                        at: elapsed,
                        releaseAt: releaseAt
                    ) ?? 1
                if let envelope = state.envelope, let releaseAt,
                    elapsed >= releaseAt + envelope.releaseTime
                {
                    state.isPlaying = false
                }
                let sample =
                    state.isPlaying
                    ? oscillatorSample(waveform: state.waveform, phase: state.phase)
                        * state.amplitude * envelopeAmplitude
                    : 0
                for buffer in buffers {
                    guard let data = buffer.mData else { continue }
                    data.assumingMemoryBound(to: Float.self)[frame] = sample
                }
                state.phase += state.frequency / sampleRate
                state.phase.formTruncatingRemainder(dividingBy: 1)
                state.samplePosition += 1
            }
        }
    }

    private func oscillatorSample(waveform: P5OscillatorWaveform, phase: Double) -> Float {
        switch waveform {
        case .sine:
            Float(sin(2 * Double.pi * phase))
        case .square:
            phase < 0.5 ? 1 : -1
        case .sawtooth:
            Float((2 * phase) - 1)
        case .triangle:
            Float(1 - (4 * abs(phase - 0.5)))
        }
    }
}

struct P5AudioFileRuntime: @unchecked Sendable {
    var open: (URL) throws -> AVAudioFile = { try AVAudioFile(forReading: $0) }
}

struct P5AudioEngineRuntime: @unchecked Sendable {
    var prepare: (AVAudioEngine) -> Void = { $0.prepare() }
    var start: (AVAudioEngine) throws -> Void = { try $0.start() }
    var pause: (AVAudioEngine) -> Void = { $0.pause() }
    var stop: (AVAudioEngine) -> Void = { $0.stop() }
    var reset: (AVAudioEngine) -> Void = { $0.reset() }
    var outputVolume: (AVAudioMixerNode) -> Float = { $0.outputVolume }
    var setOutputVolume: (AVAudioMixerNode, Float) -> Void = { $0.outputVolume = $1 }
    var outputFormat: (AVAudioMixerNode) -> AVAudioFormat = { $0.outputFormat(forBus: 0) }
    var makeFormat: (Double) -> AVAudioFormat? = {
        AVAudioFormat(standardFormatWithSampleRate: $0, channels: 1)
    }
    var makeSourceNode:
        (
            AVAudioFormat,
            @escaping @Sendable (AVAudioFrameCount, UnsafeMutableAudioBufferListPointer) -> Void
        ) ->
            AVAudioSourceNode = { format, render in
                AVAudioSourceNode(format: format) { _, _, frameCount, audioBufferList in
                    render(frameCount, UnsafeMutableAudioBufferListPointer(audioBufferList))
                    return noErr
                }
            }
    var makePlayerNode: () -> AVAudioPlayerNode = AVAudioPlayerNode.init
    var openFile: (URL) throws -> AVAudioFile = { try AVAudioFile(forReading: $0) }
    var attach: (AVAudioEngine, AVAudioNode) -> Void = { $0.attach($1) }
    var connect: (AVAudioEngine, AVAudioNode, AVAudioNode, AVAudioFormat?) -> Void = {
        $0.connect($1, to: $2, format: $3)
    }
    var installTap:
        (AVAudioMixerNode, AVAudioFrameCount, @escaping @Sendable (AVAudioPCMBuffer) -> Void) ->
            Void = {
                node, size, process in
                node.installTap(
                    onBus: 0,
                    bufferSize: size,
                    format: nil,
                    block: Self.tapHandler(process)
                )
            }
    var removeTap: (AVAudioMixerNode) -> Void = { $0.removeTap(onBus: 0) }

    static func tapHandler(
        _ process: @escaping @Sendable (AVAudioPCMBuffer) -> Void
    ) -> @Sendable (AVAudioPCMBuffer, AVAudioTime) -> Void {
        { buffer, _ in process(buffer) }
    }
}

struct P5AudioAnalysisRuntime: @unchecked Sendable {
    var makeTransform: (Int) throws -> vDSP.DiscreteFourierTransform<Float> = {
        try vDSP.DiscreteFourierTransform(
            previous: nil,
            count: $0,
            direction: .forward,
            transformType: .complexComplex,
            ofType: Float.self
        )
    }
}

struct P5AudioPlayerRuntime: @unchecked Sendable {
    var schedule:
        (
            AVAudioPlayerNode,
            AVAudioFile,
            AVAudioFramePosition,
            AVAudioFrameCount,
            @escaping @Sendable () -> Void
        ) -> Void = { node, file, start, count, completion in
            node.scheduleSegment(
                file,
                startingFrame: start,
                frameCount: count,
                at: nil,
                completionCallbackType: .dataRendered
            ) { _ in completion() }
        }
    var play: (AVAudioPlayerNode) -> Void = { $0.play() }
    var pause: (AVAudioPlayerNode) -> Void = { $0.pause() }
    var stop: (AVAudioPlayerNode) -> Void = { $0.stop() }
    var volume: (AVAudioPlayerNode) -> Float = { $0.volume }
    var setVolume: (AVAudioPlayerNode, Float) -> Void = { $0.volume = $1 }
    var pan: (AVAudioPlayerNode) -> Float = { $0.pan }
    var setPan: (AVAudioPlayerNode, Float) -> Void = { $0.pan = $1 }
}

final class P5AudioEngineCleanup: @unchecked Sendable {
    private let engine: AVAudioEngine
    private let runtime: P5AudioEngineRuntime
    private let lock = NSLock()
    private var tapInstalled = false

    init(engine: AVAudioEngine, runtime: P5AudioEngineRuntime) {
        self.engine = engine
        self.runtime = runtime
    }

    func setTapInstalled(_ installed: Bool) {
        lock.withLock { tapInstalled = installed }
    }

    deinit {
        if lock.withLock({ tapInstalled }) {
            runtime.removeTap(engine.mainMixerNode)
        }
        runtime.stop(engine)
    }
}
