import Foundation

/// A semantic keyboard key independent of AppKit and UIKit key-code values.
public enum P5Key: Sendable, Hashable, Codable {
    /// A printable extended grapheme cluster.
    case character(String)

    /// Return or Enter.
    case enter

    /// Tab.
    case tab

    /// Backspace.
    case backspace

    /// Forward Delete.
    case delete

    /// Escape.
    case escape

    /// Space.
    case space

    /// The left arrow.
    case arrowLeft

    /// The right arrow.
    case arrowRight

    /// The up arrow.
    case arrowUp

    /// The down arrow.
    case arrowDown

    /// Home.
    case home

    /// End.
    case end

    /// Page Up.
    case pageUp

    /// Page Down.
    case pageDown

    /// Shift.
    case shift

    /// Control.
    case control

    /// Option or Alt.
    case option

    /// Command.
    case command

    /// Caps Lock.
    case capsLock

    /// Function.
    case functionModifier

    /// A numbered function key in `1...24`.
    case function(Int)

    /// A platform key code that has no semantic mapping.
    case unidentified(UInt16)

    var isValid: Bool {
        switch self {
        case let .character(value): !value.isEmpty
        case let .function(number): (1...24).contains(number)
        default: true
        }
    }

    var producesTypedText: Bool {
        switch self {
        case .character, .space: true
        default: false
        }
    }
}

/// The lifecycle phase of a keyboard event.
public enum P5KeyboardPhase: Sendable, Hashable, Codable, CaseIterable {
    /// A key became pressed, or auto-repeat generated another press.
    case pressed

    /// A key was released.
    case released

    /// A printable text value was produced.
    case typed

    /// The platform cancelled an active key interaction.
    case cancelled
}

/// A platform-neutral keyboard event.
public struct P5KeyboardEvent: Sendable, Hashable, Codable {
    private enum CodingKeys: String, CodingKey {
        case phase
        case key
        case characters
        case platformKeyCode
        case modifiers
        case isRepeat
        case timestamp
    }

    /// The interaction phase.
    public let phase: P5KeyboardPhase

    /// The semantic key.
    public let key: P5Key

    /// The produced text, or `nil` for non-text keys.
    public let characters: String?

    /// The native hardware key code when supplied by the platform.
    public let platformKeyCode: UInt16?

    /// Modifier keys held after applying the event.
    public let modifiers: P5ModifierKeys

    /// Whether this press was generated by key repeat.
    public let isRepeat: Bool

    /// The platform's monotonic event timestamp in seconds.
    public let timestamp: TimeInterval

    /// Creates a validated keyboard event.
    ///
    /// Text values must be nonempty, a typed event must contain text, function
    /// keys must be in `1...24`, and the timestamp must be finite and nonnegative.
    public init(
        phase: P5KeyboardPhase,
        key: P5Key,
        characters: String? = nil,
        platformKeyCode: UInt16? = nil,
        modifiers: P5ModifierKeys = [],
        isRepeat: Bool = false,
        timestamp: TimeInterval
    ) {
        precondition(key.isValid)
        precondition(characters.map { !$0.isEmpty } ?? true)
        precondition(phase != .typed || characters != nil)
        precondition(timestamp.isFinite && timestamp >= 0)
        self.phase = phase
        self.key = key
        self.characters = characters
        self.platformKeyCode = platformKeyCode
        self.modifiers = modifiers
        self.isRepeat = isRepeat
        self.timestamp = timestamp
    }

    /// Decodes an event while preserving its semantic and finite-value invariants.
    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let phase = try container.decode(P5KeyboardPhase.self, forKey: .phase)
        let key = try container.decode(P5Key.self, forKey: .key)
        let characters = try container.decodeIfPresent(String.self, forKey: .characters)
        let timestamp = try container.decode(TimeInterval.self, forKey: .timestamp)
        guard
            key.isValid,
            characters.map({ !$0.isEmpty }) ?? true,
            phase != .typed || characters != nil,
            timestamp.isFinite,
            timestamp >= 0
        else {
            throw DecodingError.dataCorruptedError(
                forKey: .key,
                in: container,
                debugDescription: "Keyboard key, text, phase, or timestamp is invalid."
            )
        }

        self.init(
            phase: phase,
            key: key,
            characters: characters,
            platformKeyCode: try container.decodeIfPresent(UInt16.self, forKey: .platformKeyCode),
            modifiers: try container.decode(P5ModifierKeys.self, forKey: .modifiers),
            isRepeat: try container.decode(Bool.self, forKey: .isRepeat),
            timestamp: timestamp
        )
    }
}
